name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test & Validate
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: '2.2.0'

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine wine32 wine64
          wine --version

      - name: Run tests
        run: mvn clean test

      - name: Build and install plugin
        run: mvn clean install

      - name: Verify plugin works
        run: |
          mkdir -p test-project
          cat > test-project/pom.xml << 'EOF'
          <project>
            <modelVersion>4.0.0</modelVersion>
            <groupId>test</groupId>
            <artifactId>test</artifactId>
            <version>1.0</version>
            <build>
              <plugins>
                <plugin>
                  <groupId>io.github.kaffamobile.tools.maven</groupId>
                  <artifactId>gjg-maven-plugin</artifactId>
                  <version>0.0.2-SNAPSHOT</version>
                  <configuration>
                    <outputFile>target/test.exe</outputFile>
                    <jarFile>test.jar</jarFile>
                  </configuration>
                </plugin>
              </plugins>
            </build>
          </project>
          EOF
          
          mkdir -p test-project/target
          echo "test" > test-project/target/test.jar
          
          cd test-project
          mvn gjg:package || echo "Plugin execution test completed"